#Configuration BD Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/buyconnexDB
spring.datasource.username=postgres
spring.datasource.password=adminLes22.

spring.jpa.properties.hibernate,dialect=org.hibernate.dialect.PostgresPlusDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop

#JavaMail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.username=brainsconnex@gmail.com
spring.mail.password=brainLes22.
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.transport.protocol=smtp
spring.mail.properties.mail.smtp.transport.timeout=8000
spring.mail.debug=false


#Ignore null fields in JSON
spring.jackson.default-property-inclusion=NON_NULL
spring.main.allow-circular-references=true

#Cron batch
purge.cron.expression=5 * * * * ?
create.user.cron.expression=1 * * * * ?

management.security.enabled=false
management.endpoints.web.exposure.inclure=*
management.endpoint.health.show-details=always
management.endpoint.shutdown.enabled=true

#Configuration applicatif
server.port=8080
server.servlet.context-path=/buyconnex-back

#JWT Configuration
#3 minutes de validité
jwt.token.validity=6480000

application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# a day
application.security.jwt.expiration=86400000 
application.security.jwt.refresh-token.expiration=86400000

